--1) What is the unique count and total amount for each transaction type?
SELECT TXN_TYPE
    ,COUNT(DISTINCT *) AS UNIQUE_COUNT
    ,SUM(TXN_AMOUNT) AS TOTAL
FROM CUSTOMER_TRANSACTIONS
GROUP BY TXN_TYPE;

--2) What is the average total historical deposit counts and amounts for all customers?
WITH CTE AS(
    SELECT CUSTOMER_ID
        ,COUNT(*) AS COUNT_ALL
        ,AVG(TXN_AMOUNT) AS AVERAGE
    FROM CUSTOMER_TRANSACTIONS
    WHERE TXN_TYPE <> 'deposit'
    GROUP BY CUSTOMER_ID
)

SELECT ROUND(AVG(COUNT_ALL),1)
    ,ROUND(AVG(AVERAGE),1)
FROM CTE;

--3) For each month - how many Data Bank customers make more than 1 deposit and either 1 purchase or 1 withdrawal in a single month?
WITH DEPOSITS AS(
    SELECT MONTH(TXN_DATE) AS MONTH
        ,CUSTOMER_ID
        ,COUNT(*) AS NO_OF_DEPOSITS
    FROM CUSTOMER_TRANSACTIONS
    WHERE TXN_TYPE = 'deposit'
    GROUP BY MONTH
        ,CUSTOMER_ID
)
, PURCHASE AS (
    SELECT MONTH(TXN_DATE) AS MONTH
        ,CUSTOMER_ID
        ,COUNT(*) AS NO_OF_PURCHASES
    FROM CUSTOMER_TRANSACTIONS
    WHERE TXN_TYPE = 'purchase'
    GROUP BY MONTH
        ,CUSTOMER_ID
)
, WITHDRAWAL AS (
    SELECT MONTH(TXN_DATE) AS MONTH
        ,CUSTOMER_ID
        ,COUNT(*) AS NO_OF_WITHDRAWALS
    FROM CUSTOMER_TRANSACTIONS
    WHERE TXN_TYPE = 'withdrawal'
    GROUP BY MONTH
        ,CUSTOMER_ID
)
SELECT D.MONTH,
    SUM(CASE WHEN NO_OF_DEPOSITS AND (NO_OF_PURCHASES= 1 OR NO_OF_WITHDRAWALS = 1) THEN 1
                ELSE 0
                END) AS NO_OF_CUSTOMERS
FROM DEPOSITS D
LEFT JOIN PURCHASE P
    ON D.CUSTOMER_ID = P.CUSTOMER_ID
    AND D.MONTH = P.MONTH
LEFT JOIN WITHDRAWAL W
    ON D.CUSTOMER_ID = W.CUSTOMER_ID
    AND D.MONTH = W.MONTH
GROUP BY D.MONTH;

--4) What is the closing balance for each customer at the end of the month?
WITH MAX_DATE AS (
    SELECT MAX(TXN_DATE) AS MAX_DATE
        ,MONTH(TXN_DATE) AS MONTH
        ,CUSTOMER_ID
    FROM CUSTOMER_TRANSACTIONS
    GROUP BY MONTH
        ,CUSTOMER_ID
)
,RUNNING_TOTAL AS(
    SELECT CUSTOMER_ID
        ,MONTH(TXN_DATE) AS MONTH
        ,TXN_DATE
        ,SUM(TXN_AMOUNT) OVER(PARTITION BY CUSTOMER_ID ORDER BY TXN_DATE) AS CLOSING_BALANCE
    FROM CUSTOMER_TRANSACTIONS
)
SELECT DISTINCT RT.CUSTOMER_ID
    ,RT.MONTH
    ,CLOSING_BALANCE
FROM RUNNING_TOTAL RT
INNER JOIN MAX_DATE MD
 ON RT.CUSTOMER_ID = MD.CUSTOMER_ID
 AND RT.MONTH = MD.MONTH
WHERE RT.TXN_DATE = MD.MAX_DATE
ORDER BY CUSTOMER_ID, MONTH ASC

